### ISSUE TITLE
Cannot work with Redshift version 1.0.18788 

### ISSUE THREAD

**Issue by youngffan0114** [awslabs/amazon-redshift-monitoring#27]
The metrics cannot be generated with version 1.0.18788. The possible cause might be connection failure. Here is the stack trace: 

```
The read operation timed out: timeout
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 15, in lambda_handler
    redshift_monitoring.monitor_cluster(config_sources)
  File "/var/task/redshift_monitoring.py", line 329, in monitor_cluster
    put_metrics.extend(gather_service_class_stats(cursor, cluster))
  File "/var/task/redshift_monitoring.py", line 124, in gather_service_class_stats
    ''')
  File "/var/task/redshift_monitoring.py", line 98, in run_command
    cursor.execute(statement)
  File "/var/task/lib/pg8000/core.py", line 861, in execute
    self._c.execute(self, operation, args)
  File "/var/task/lib/pg8000/core.py", line 1909, in execute
    self.handle_messages(cursor)
  File "/var/task/lib/pg8000/core.py", line 1972, in handle_messages
    code, data_len = ci_unpack(self._read(5))
  File "/var/lang/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/var/lang/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/var/lang/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/var/lang/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
```

In comparison, we have another cluster with **the latest version** (1.0.18861) which generated and updated the metrics successfully. Based on the comparison, we assume that the Redshift version might influence the project. 

**NOTE**
We modified the code to make timeout as an input parameter. The code changes are listed below:  
redshift-monitoring.py

```
line 262      #Add timeout to config_sources
line 263     timeout = int(get_config_value(['TimeOut', 'time_out', 'timeOut'], config_sources))
..........
line 305     conn = pg8000.connect(database=database, user=user, password=pwd, host=host, port=port, ssl=ssl, timeout=timeout)
```

The input JSON of the cloud watch event rule: 
`{   "DbUser": "xxxxxxx",   "EncryptedPassword": "**************",   "ClusterName": "xxxxxxxxxx",   "HostName": "xxxxxxxxxxxxxx",   "HostPort": "xxxx",   "DatabaseName": "xxxxxxxxxx",   "AggregationInterval": "1 hour", "TimeOut": "20" }`

P.S
- Project version: 1.7
- Deployment method: manually create AWS resources and upload zip onto Lambda function

**Comment by IanMeyers** [comment]
Can you please verify that there's no difference in TLS settings between the two clusters?

Thx,

Ian

**Comment by youngffan0114** [comment]
> Can you please verify that there's no difference in TLS settings between the two clusters?
> 
> Thx,
> 
> I
